name: mg_shared_storage
description: "Flutter plugin to work with external storage and privacy-friendly APIs."
version: 0.8.2
homepage: https://github.com/alexrintt/shared-storage
repository: https://github.com/alexrintt/shared-storage
issue_tracker: https://github.com/alexrintt/shared-storage/issues
documentation: https://github.com/alexrintt/shared-storage

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: io.alexrintt.sharedstorage
        pluginClass: SharedStoragePlugin
