name: Publish new plugin version
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: "stable"
      - run: |
          flutter --version
          flutter pub get
          flutter analyze --fatal-infos

      - name: Create credentials file
        run: echo $PUB_CREDENTIALS > ~/pub-credentials.json
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}

      - name: Add credentials to Dart folder
        run: |
          mkdir -p ${XDG_CONFIG_HOME:-${HOME:-default}}/dart
          touch ${XDG_CONFIG_HOME:-${HOME:-default}}/dart/pub-credentials.json
          cp ~/pub-credentials.json ${XDG_CONFIG_HOME:-${HOME:-default}}/dart/pub-credentials.json
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}

      - name: Publish
        run: dart pub publish --force
