name: Perform static code analysis through Dart CLI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - release

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: "stable"
      - run: |
          flutter --version
          flutter pub get
          flutter analyze --fatal-infos
